apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deployment
  labels:
    app: vprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
        - name: vprofile
          image: cdivyaanshu/vprofile:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: "mysql-service"
            - name: DATABASE_PORT
              value: "3306"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
